apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: agentic-cluster
servers: 1
agents: 0
image: rancher/k3s:v1.31.5-k3s1
ports:
  - port: 8080:80 # Port NiceGUI (via Ingress)
    nodeFilters:
      - loadbalancer
  - port: 6006:6006 # Port Arize Phoenix
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*